<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cutplace-version [<!ELEMENT cutplace-version (version,release,revision,date)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT revision (#PCDATA)>
<!ELEMENT release (#PCDATA)>
<!ELEMENT date (#PCDATA)>
]>
<cutplace-version>
  <version>0</version>
  <release>3</release>
  <revision>0</revision>
  <date>2009-04-28</date>
</cutplace-version>
